spring:
  application:
    name: backend-2generales
  datasource:
    url: jdbc:mysql://localhost:3306/dos_generales_db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:TU_USUARIO}
    password: ${DB_PASSWORD:TU_CONTRASEÃ‘A}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

cloudinary:
  cloudName: ${CLOUD-NAME}
  apiKey: ${CLOUD-KEY}
  apiSecret: ${CLOUD-SECRET}

app:
  price-list:
    validity-days: 45